services:
  dtw_backend:
    build:
      context: $HOME/github.com/loicbourgois/downtowhat
      dockerfile: backend/Dockerfile
    command: backend/inner_go.sh
    environment:
      - DATABASE_PASSWORD=downtowhat_password
      - DATABASE_USER=downtowhat
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=downtowhat
      - API_PORT=80
      - API_HOST=0.0.0.0
      - front_dir=/root/github.com/loicbourgois/downtowhat/front
      - salt=95546f94a0226eb26c9a7728133282de
    volumes:
      - $HOME/github.com/loicbourgois/downtowhat/backend:/root/github.com/loicbourgois/downtowhat/backend:ro
      - $HOME/github.com/loicbourgois/downtowhat/front:/root/github.com/loicbourgois/downtowhat/front:ro
    ports:
      - 80:80
