services:
  data_builder:
    build:
      context: $HOME/github.com/loicbourgois/downtowhat/data_builder
      dockerfile: Dockerfile
    command: /root/github.com/loicbourgois/downtowhat/data_builder/_main.sh
    volumes:
      - $HOME/github.com/loicbourgois/downtowhat_local/data:/root/github.com/loicbourgois/downtowhat_local/data:rw
      - $HOME/github.com/loicbourgois/downtowhat:/root/github.com/loicbourgois/downtowhat:ro
