[package]
name = "movie_finder_database"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
# https://docs.rs/csv/latest/csv/
csv = "1.4"
# https://docs.rs/rayon/latest/rayon/
rayon = "1.11"
# https://docs.rs/num_cpus/latest/num_cpus/
num_cpus = "1.17"


# [lib]
# crate-type = ["cdylib", "rlib"]


[features]
bench = []