version: "3"
services:
    movie_front:
        image: nginx
        ports:
            - 80:80
        volumes:
            - $HOME/github.com/loicbourgois/downtowhat/movie_front:/usr/share/nginx/html/movie_front
            - $HOME/github.com/loicbourgois/downtowhat/movie_front/favicon.ico:/usr/share/nginx/html/favicon.ico
            - $HOME/github.com/loicbourgois/downtowhat_local/data:/usr/share/nginx/html/data
