services:
  dtw_database_query:
    build:
      context: $HOME/github.com/loicbourgois/downtowhat
      dockerfile: database/query/Dockerfile
    command: database/query/query_inner.sh
    environment:
      - DATABASE_PASSWORD=downtowhat_password
      - DATABASE_USER=downtowhat
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - DATABASE_NAME=downtowhat
    volumes:
      - $HOME/github.com/loicbourgois/downtowhat/database/query:/root/github.com/loicbourgois/downtowhat/database/query:rw
    # links:
    #   - dtw_database:db
